version: '3.8'
services:
  go-admin-api:
    container_name: go-admin
    image: aixiaoqi-server:latest
    environment:
      - WEAPP_APPID=${WEAPP_APPID}
      - WEAPP_APPSECRET=${WEAPP_APPSECRET}
      - Jwt_SECRET=${Jwt_SECRET}
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
    privileged: true
    restart: always
    ports:
      - 8200:8000
    volumes:
      - ./config/:/go-admin-api/config/
      - ./static/:/go-admin-api/static/
      - ./temp/:/go-admin-api/temp/
    networks:
      - myweb
networks:
  myweb:
    driver: bridge

